# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Test_AEC' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Test_AEC

  pod 'IQKeyboardManager'

  target 'Test_AECTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test_AECUITests' do
    inherit! :search_paths

    # Pods for testing
  end

end
